#!/bin/bash

if [ -z "$PYFILE" ]; then
	echo "PYFILE environment variable is not set."
	exit 1
fi

OUTFILE="${PYFILE}c"

python3 -m compileall -b "$PYFILE" && echo "Compiling $PYFILE ..." && mv "__pycache__/$OUTFILE" . && rm -rf "__pycache__"
